In [1]:
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sklearn
from sklearn.model_selection import train_test_split
import pandas as pd
import os
import random

In [2]:
#define converts(字典)  
# def Name_label(s):
#     it = {b'cjn':10, b'lmx':20, b'yxd':30, b'zzy':40 }
#     return it[s]

def Name_label(s):
    return int(s) - 1

In [3]:
# #1.读取数据集
# import import_ipynb # 为了import ipynb文件特地安装的库
# from utils import svm_data_gen
# name = "dynamic_feature-2-26" # 更换不同数据只需要修改name的参数即可，其它变量无需改动
# data_name = name + ".data"
# data_path = '../gen_data/' + data_name
# filePath = '../raw_data/' + name + '/'

# try:
#     data = np.loadtxt(data_path, dtype=float, delimiter=',', converters={24:Name_label})
# #     converters={4:Iris_label}中“24”指的是第25列：将第25列的str转化为label(number)
# except IOError as err:  #使用as将异常对象，并将其赋值给一个标识符
#     print('File Error:'+str(err)) #‘+’用于字符串直接的连接
#     print("正在从csv生成.data数据中")
    
#     # 从csv数据转换成.data的txt数据
#     svm_data_gen(filePath, data_name)
#     data = np.loadtxt(data_path, dtype=float, delimiter=',', converters={24:Name_label})
#     print("生成数据完毕！")

# print("加载数据完毕！")
# print("data shape: ", data.shape)

In [4]:
# PCA 降维处理  可选
# 训练集： 1.0
# 测试集： 0.538461538461538
# 使用PCA的时候，需要修改下面划分数据与标签

# from sklearn.decomposition import PCA
# pca = PCA(n_components='mle') # 降维由算法自选
# label_data = data[:, -1:]
# print("label_data shape: ", label_data.shape)
# data = data[:, :-1]
# data = pca.fit_transform(data)
# print("data shape: ", data.shape)
# data = np.concatenate((data, label_data), axis=1)
# print("pca data shape: ", data.shape)

In [5]:
# #2.划分数据与标签
# x, y = np.split(data,indices_or_sections=(24,),axis=1) #x为数据，y为标签  前24个为特征，最后一个为标签
# # x = x[:, ::3] # 只取8个特征， 目前效果看起来与24个特征差不多
# print("data size: ", x.shape)
# random.seed(42) # 指定随机数种子，确保每次划分结果一致
# train_data,test_data,train_label,test_label = train_test_split(x, y, random_state=1, train_size=0.8, test_size=0.2) #sklearn.model_selection.  
# print("train data sgape: ", train_data.shape)

In [6]:
csv_path = '../gen_data/dynamic_features.csv'
column_name = ['A_pos_peak_time', 'MAX_pos_peak_time', 'MIN_pos_peak_time', 'A_neg_peak_time', 'MAX_neg_peak_time', 'MIN_neg_peak_time',
 'A_close time', 'MAX_close time', 'MIN_close time', 'A_open time', 'MAX_open time', 'MIN_open time', 'A_blink time', 
 'MAX_blink time', 'MIN_blink time', 'A_peak ratio', 'MAX_peak ratio', 'MIN_peak ratio', 'A_peak dist ratio', 'MAX_peak dist ratio', 
 'MIN_peak dist ratio', 'A_area ratio', 'MAX_area ratio', 'MIN_area ratio', 'Label']
data = pd.read_csv(csv_path)
data.head()

A_pos_peak_time  MAX_pos_peak_time  MIN_pos_peak_time  A_neg_peak_time  \
0             36.8               49.2               71.2            146.8   
1             38.4               47.6               78.8            172.8   
2             37.2               52.0               81.2            157.2   
3             33.6               47.6               74.4            159.6   
4             35.2               48.8               76.8            156.0   

   MAX_neg_peak_time  MIN_neg_peak_time  A_close time  MAX_close time  \
0              218.0               2.78          0.38            1.24   
1              251.6               2.38          0.35            1.05   
2              238.4               2.47          0.40            1.09   
3              234.0               2.63          0.38            1.15   
4              232.8               2.65          0.39            1.12   

   MIN_close time  A_open time  ...  A_peak ratio  MAX_peak ratio  \
0            44.0         58.0  ...          1.46            34.0   
1            50.0         56.0  ...          1.28            32.0   
2            54.0         68.0  ...          1.25            32.0   
3            36.0         58.0  ...          1.25            30.0   
4            42.0         58.0  ...          1.23            32.0   

   MIN_peak ratio  A_peak dist ratio  MAX_peak dist ratio  \
0            38.0               68.0                134.0   
1            38.0               70.0                156.0   
2            44.0               66.0                152.0   
3            40.0               68.0                148.0   
4            40.0               70.0                150.0   

   MIN_peak dist ratio  A_area ratio  MAX_area ratio  MIN_area ratio  Label  
0                204.0          2.20            0.34            1.06    0.0  
1                228.0          0.90            0.25            0.60    0.0  
2                222.0          2.33            0.34            1.02    0.0  
3                222.0          2.46            0.33            1.08    0.0  
4                224.0          2.42            0.35            1.01    0.0  

[5 rows x 25 columns]

# 分层采样

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit 
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=25)
for train_index, test_index in split.split(data, data["Label"]): 
    strat_train_set = data.loc[train_index] 
    strat_test_set = data.loc[test_index]
# train_index, test_index = split.split(data, data["Label"])
print(len(strat_train_set))
print(len(strat_test_set))
print(len(data))

210
53
263


In [8]:
strat_train_set = np.array(strat_train_set)
strat_test_set = np.array(strat_test_set)
train_data,train_label = np.split(strat_train_set,indices_or_sections=(24,),axis=1) #x为数据，y为标签  前24个为特征，最后一个为标签
test_data, test_label = np.split(strat_test_set,indices_or_sections=(24,),axis=1) #x为数据，y为标签  前24个为特征，最后一个为标签

# 训练

In [9]:
#3.训练svm分类器
# ==========F:1
# 训练 1.0
# 测试 0.69
# classifier = svm.SVC(C=2, kernel='rbf', gamma=10, decision_function_shape='ovo') # ovr:一对多策略  尽量使用ovo比较好
# classifier.fit(train_data,train_label.ravel()) # ravel函数在降维时默认是行序优先

# ==========F:2
# 训练 1.0
# 测试 0.76
classifier = svm.SVC(C=2, kernel='poly', degree=2, gamma='auto', decision_function_shape='ovo') # ovr:一对多策略  尽量使用ovo比较好
classifier.fit(train_data,train_label.ravel()) # ravel函数在降维时默认是行序优先


SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=2, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
# #4.计算svc分类器的准确率  
# print("训练集：",classifier.score(train_data,train_label))
# print("测试集：",classifier.score(test_data,test_label))

In [11]:
# #也可直接调用accuracy_score方法计算准确率  
# from sklearn.metrics import accuracy_score
# tra_label = classifier.predict(train_data) # 训练集的预测标签
# tes_label = classifier.predict(test_data) # 测试集的预测标签 
# print("训练集：",  accuracy_score(train_label,tra_label))
# print("测试集：", accuracy_score(test_label,tes_label))

In [12]:
# #查看决策函数
# print('train_decision_function:\n',classifier.decision_function(train_data)) # (90,3)
# print('predict_result:\n',classifier.predict(train_data))

In [13]:
from sklearn.model_selection import cross_val_score
cross_val_score(classifier, train_data, train_label.ravel(), cv=7, scoring="accuracy")

array([0.54285714, 0.75      , 0.64516129, 0.6       , 0.78571429,
       0.62962963, 0.66666667])

In [18]:
from sklearn.model_selection import cross_val_predict 
svm_clf = svm.SVC(C=2, kernel='poly', degree=2, gamma='auto', decision_function_shape='ovo')
train_data_pred = cross_val_predict(svm_clf, train_data, train_label.ravel(), cv=7)

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(train_label.ravel(), train_data_pred)

array([[25,  0,  2,  3,  0,  1,  0,  0,  1,  0],
       [ 1, 28,  0,  0,  0,  5,  1,  0,  2,  0],
       [ 2,  0, 22,  0,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  3,  0,  0,  1,  0,  0,  2],
       [ 0,  4,  0,  0,  7,  2,  0,  0,  0,  1],
       [ 0,  2,  0,  1,  2,  9,  2,  5,  1,  0],
       [ 0,  1,  0,  2,  0,  0, 12,  1,  1,  0],
       [ 1,  1,  0,  2,  1,  0,  2,  6,  1,  1],
       [ 1,  3,  0,  0,  0,  1,  1,  0, 12,  0],
       [ 1,  0,  1,  5,  0,  0,  0,  0,  1, 14]], dtype=int64)

In [24]:
# classifier.fit(train_data,train_label.ravel()) # ravel函数在降维时默认是行序优先
# sklearn.model_selection.cross_validate()
test_data_pred = classifier.predict(test_data)
confusion_matrix(test_label.ravel(), test_data_pred)

array([[7, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 9, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 3, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 2, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 3, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 3]], dtype=int64)

# precision & recall

In [25]:
from sklearn.metrics import classification_report
print(classification_report(test_label.ravel(), test_data_pred))
# precision_score(test_label.ravel(), test_data_pred)
# recall_score(test_label.ravel(), test_data_pred)

              precision    recall  f1-score   support

         0.0       0.78      0.88      0.82         8
         1.0       0.75      1.00      0.86         9
         2.0       0.70      1.00      0.82         7
         3.0       0.50      0.50      0.50         2
         4.0       1.00      0.75      0.86         4
         5.0       1.00      0.50      0.67         6
         6.0       0.67      0.50      0.57         4
         7.0       0.75      0.75      0.75         4
         8.0       1.00      0.75      0.86         4
         9.0       0.75      0.60      0.67         5

   micro avg       0.77      0.77      0.77        53
   macro avg       0.79      0.72      0.74        53
weighted avg       0.80      0.77      0.76        53



In [26]:
print(classification_report(train_label.ravel(), train_data_pred))

              precision    recall  f1-score   support

         0.0       0.81      0.78      0.79        32
         1.0       0.72      0.76      0.74        37
         2.0       0.85      0.85      0.85        26
         3.0       0.19      0.43      0.26         7
         4.0       0.58      0.50      0.54        14
         5.0       0.50      0.41      0.45        22
         6.0       0.63      0.71      0.67        17
         7.0       0.50      0.40      0.44        15
         8.0       0.63      0.67      0.65        18
         9.0       0.78      0.64      0.70        22

   micro avg       0.66      0.66      0.66       210
   macro avg       0.62      0.61      0.61       210
weighted avg       0.67      0.66      0.66       210

